// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEIJpj9BDypaDVHrO5ft54auJ5tAYOQwM',
    appId: '1:91925291947:android:2be1ec9bf177cc649128ee',
    messagingSenderId: '91925291947',
    projectId: 'reelapp-acab6',
    databaseURL: 'https://reelapp-acab6-default-rtdb.firebaseio.com',
    storageBucket: 'reelapp-acab6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2qy6TqBuKZx2qAJb57x0f2QXSZuQHptw',
    appId: '1:91925291947:ios:58f703ccc4492fba9128ee',
    messagingSenderId: '91925291947',
    projectId: 'reelapp-acab6',
    databaseURL: 'https://reelapp-acab6-default-rtdb.firebaseio.com',
    storageBucket: 'reelapp-acab6.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );
}
